# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcActivity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=64, null=True)),
                ('affecteduser', models.CharField(max_length=64)),
                ('app', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('subjectparams', models.CharField(max_length=4000)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('messageparams', models.CharField(blank=True, max_length=4000, null=True)),
                ('file', models.CharField(blank=True, max_length=4000, null=True)),
                ('link', models.CharField(blank=True, max_length=4000, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.IntegerField()),
            ],
            options={
                'db_table': 'oc_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'actions',
                'managed': True,
            },
        ),
    ]
