# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDBv2', '0002_datatable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTable',
        ),
    ]
